### ISSUE TITLE
Add Commands for Shop Edit Actions

### ISSUE THREAD

**Issue by XZot1K** [XZot1K/DisplayShopsAPI#11]
**TODO**
- [ ] Add stock deposit and withdraw commands.
- [ ] Add balance deposit and withdraw commands.
- [ ] Add change shop and trade item commands.
